version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: strf-server
    restart: always
    expose:
      - "5002"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5002
    networks:
      - app-network
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: strf-client
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
