version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    restart: always
    expose:
      - "5000"
    env_file:
      - .env
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
